name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest

  build-doc:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Install Dependencies
        working-directory: ./doc
        run: bun install

      - name: Compile Documentation
        working-directory: ./doc
        run: bun run build

  build-rust:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Compile Rust
        run: cargo build

  package-wasm:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Package WASM
        working-directory: ./api
        run: wasm-pack build

  build-client:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Install Dependencies
        working-directory: ./client
        run: bun install

      - name: Compile Client
        working-directory: ./client
        run: bun run build
